version: "3"
services:
  database:
    image: postgres:15.3
    user: postgres
    restart: always
    environment:
      # POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./library/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build:
      context: ./
      dockerfile: Dockerfile.development
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
    # environment:
    #   DB_HOST: db
    #   DB_USER: ${POSTGRES_USER}
    #   DB_PASSWORD: ${POSTGRES_PASSWORD}
    #   DB_NAME: ${POSTGRES_DB}
    #   PORT: ${PORT}
    volumes:
      - ./:/app/
      - ignore:/app/node_modules/
volumes:
  postgres_data:
  ignore:
