version: "3"
services:
  database:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - database
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  app:
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile.development
    restart: always
    ports:
      - "8080:8080"
      # - ${PORT}:${PORT}
    depends_on:
      - database
    volumes:
      - ./:/app/
      - node-modules:/app/node_modules/
volumes:
  postgres_data:
  pgadmin-data:
  node-modules:
