name: Test & Build

on: [pull_request]

jobs:
  api:
    name: Install,Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build
      - run: npm run test
